### ISSUE TITLE
SFDX creates a scratch org on API 41, not 42

### ISSUE THREAD

**Issue by dcinzona** [muenzpraeger/spring18-recordEditForm-inputField#1]
Ran through the steps and the new scratch org that was created was on Winter '18, not Spring '18 even though I see the API version specified in the config.  Not sure if this is a temporary issue, or timing related, or hub org version related.

This obviously leads to not being able to push the source.
```
$ sfdx force:source:push
PROJECT PATH  ERROR
────────────  ──────────────────────────────
N/A           Invalid version specified:42.0
```

**Comment by muenzpraeger** [comment]
As we're still not in full release mode you need a Spring '18 enabled dev hub (https://www.salesforce.com/form/signup/prerelease-spring18.jsp, choose Enterprise Edition).

The parameter in the config (sourceApiVersion) has nothing to do with that (see bottom, https://www.salesforce.com/form/signup/prerelease-spring18.jsp).
